# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 11:42
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Robject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modify_date', models.DateTimeField(auto_now=True, null=True)),
                ('notes', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('ligand', models.CharField(blank=True, max_length=100, null=True)),
                ('receptor', models.CharField(blank=True, max_length=100, null=True)),
                ('ref_seq', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('mod_seq', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('bibliography', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('ref_commercial', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('ref_clinical', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='robjects_in_which_user_is_author', to=settings.AUTH_USER_MODEL)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='robjects_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('modify_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.AddField(
            model_name='robject',
            name='tags',
            field=models.ManyToManyField(to='robjects.Tag'),
        ),
    ]
