# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='robject',
            name='name',
            field=models.ForeignKey(help_text='The name of robject', on_delete=django.db.models.deletion.CASCADE, related_name='robject_name', to='robjects.Name'),
        ),
    ]
