# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robjects', '0002_auto_20170808_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='robject',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='robject',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
